insert into public.permissions(key,module,description)
values
 ('treasury.view','treasury','View branch treasury accounts and movements'),
 ('treasury.accounts.manage','treasury','Manage branch cash and bank treasury accounts'),
 ('treasury.movements.create','treasury','Create branch treasury in/out movements')
on conflict (key) do nothing;

create table public.treasury_accounts (
 id uuid primary key default gen_random_uuid(), branch_id uuid not null references public.branches(id), code text not null check (btrim(code)<>''), name_ar text not null check (btrim(name_ar)<>''), name_en text,
 treasury_type text not null check (treasury_type in ('cash','bank')), account_id uuid not null, bank_name text, bank_account_reference text, is_active boolean not null default true,
 created_by uuid not null default auth.uid() references auth.users(id), updated_by uuid not null default auth.uid() references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(branch_id,code), unique(id,branch_id), foreign key(account_id,branch_id) references public.accounts(id,branch_id));

create table public.treasury_movements (
 id uuid primary key default gen_random_uuid(), branch_id uuid not null references public.branches(id), treasury_account_id uuid not null, movement_number bigint not null, movement_date date not null default current_date,
 direction text not null check(direction in('in','out')), amount numeric(14,2) not null check(amount>0), counter_account_id uuid not null, description text not null check(btrim(description)<>''), reference text,
 idempotency_key text not null check(btrim(idempotency_key)<>''), journal_entry_id uuid not null, created_by uuid not null default auth.uid() references auth.users(id), created_at timestamptz not null default now(),
 unique(branch_id,movement_number), unique(branch_id,idempotency_key), unique(id,branch_id),
 foreign key(treasury_account_id,branch_id) references public.treasury_accounts(id,branch_id), foreign key(counter_account_id,branch_id) references public.accounts(id,branch_id), foreign key(journal_entry_id,branch_id) references public.journal_entries(id,branch_id));

create index idx_treasury_accounts_branch_active on public.treasury_accounts(branch_id,is_active,treasury_type,code);
create index idx_treasury_accounts_account_branch on public.treasury_accounts(account_id,branch_id);
create index idx_treasury_accounts_created_by on public.treasury_accounts(created_by);
create index idx_treasury_accounts_updated_by on public.treasury_accounts(updated_by);
create index idx_treasury_movements_branch_date on public.treasury_movements(branch_id,movement_date desc,movement_number desc);
create index idx_treasury_movements_account_branch on public.treasury_movements(treasury_account_id,branch_id);
create index idx_treasury_movements_counter_branch on public.treasury_movements(counter_account_id,branch_id);
create index idx_treasury_movements_journal_branch on public.treasury_movements(journal_entry_id,branch_id);
create index idx_treasury_movements_created_by on public.treasury_movements(created_by);

create view public.treasury_balances with (security_invoker=true) as
select ta.branch_id,ta.id as treasury_account_id,coalesce(sum(case when tm.direction='in' then tm.amount else -tm.amount end),0)::numeric(14,2) as balance
from public.treasury_accounts ta left join public.treasury_movements tm on tm.treasury_account_id=ta.id and tm.branch_id=ta.branch_id group by ta.branch_id,ta.id;

alter table public.treasury_accounts enable row level security; alter table public.treasury_movements enable row level security;
create policy treasury_accounts_select on public.treasury_accounts for select to authenticated using(app_private.current_user_may_access_branch(branch_id) and (app_private.current_user_has_permission('treasury.view',branch_id) or app_private.current_user_has_permission('treasury.accounts.manage',branch_id) or app_private.current_user_has_permission('treasury.movements.create',branch_id)));
create policy treasury_movements_select on public.treasury_movements for select to authenticated using(app_private.current_user_may_access_branch(branch_id) and (app_private.current_user_has_permission('treasury.view',branch_id) or app_private.current_user_has_permission('treasury.accounts.manage',branch_id) or app_private.current_user_has_permission('treasury.movements.create',branch_id)));
revoke all on public.treasury_accounts,public.treasury_movements from anon,authenticated; grant select on public.treasury_accounts,public.treasury_movements to authenticated;
revoke all on public.treasury_balances from anon,authenticated; grant select on public.treasury_balances to authenticated;

drop policy if exists accounts_select on public.accounts;
create policy accounts_select on public.accounts for select to authenticated using(app_private.current_user_may_access_branch(branch_id) and (
 app_private.current_user_has_permission('accounting.coa.view',branch_id) or app_private.current_user_has_permission('accounting.coa.manage',branch_id)
 or app_private.current_user_has_permission('accounting.journals.view',branch_id) or app_private.current_user_has_permission('accounting.journals.create',branch_id) or app_private.current_user_has_permission('accounting.journals.edit',branch_id) or app_private.current_user_has_permission('accounting.journals.post',branch_id)
 or app_private.current_user_has_permission('accounting.expenses.view',branch_id) or app_private.current_user_has_permission('accounting.expenses.create',branch_id) or app_private.current_user_has_permission('accounting.expenses.edit',branch_id) or app_private.current_user_has_permission('accounting.expenses.post',branch_id)
 or app_private.current_user_has_permission('treasury.view',branch_id) or app_private.current_user_has_permission('treasury.accounts.manage',branch_id) or app_private.current_user_has_permission('treasury.movements.create',branch_id)));

create or replace function app_private.validate_treasury_coa_account_internal(p_branch_id uuid,p_account_id uuid) returns void language plpgsql security definer set search_path='' as $$
declare v_account public.accounts%rowtype; begin select * into v_account from public.accounts where id=p_account_id and branch_id=p_branch_id; if not found or not v_account.is_active or not v_account.is_postable or v_account.account_type<>'asset' then raise exception 'treasury COA account must be active postable asset account'; end if; end $$;

create or replace function app_private.create_treasury_account_internal(p_branch_id uuid,p_code text,p_name_ar text,p_name_en text,p_treasury_type text,p_account_id uuid,p_bank_name text,p_bank_account_reference text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_id uuid; begin if auth.uid() is null then raise exception 'authentication required'; end if; if not app_private.has_permission('treasury.accounts.manage',p_branch_id,auth.uid()) then raise exception 'permission denied'; end if; if nullif(btrim(p_code),'') is null or nullif(btrim(p_name_ar),'') is null then raise exception 'treasury code and Arabic name required'; end if; if p_treasury_type not in ('cash','bank') then raise exception 'invalid treasury type'; end if; perform app_private.validate_treasury_coa_account_internal(p_branch_id,p_account_id); if exists(select 1 from public.treasury_accounts where branch_id=p_branch_id and account_id=p_account_id) then raise exception 'COA account already linked to treasury account'; end if; insert into public.treasury_accounts(branch_id,code,name_ar,name_en,treasury_type,account_id,bank_name,bank_account_reference,created_by,updated_by) values(p_branch_id,btrim(p_code),btrim(p_name_ar),nullif(btrim(p_name_en),''),p_treasury_type,p_account_id,case when p_treasury_type='bank' then nullif(btrim(p_bank_name),'') else null end,case when p_treasury_type='bank' then nullif(btrim(p_bank_account_reference),'') else null end,auth.uid(),auth.uid()) returning id into v_id; return v_id; end $$;
create or replace function public.create_treasury_account(p_branch_id uuid,p_code text,p_name_ar text,p_name_en text,p_treasury_type text,p_account_id uuid,p_bank_name text default null,p_bank_account_reference text default null) returns uuid language sql security invoker set search_path='' as $$select app_private.create_treasury_account_internal(p_branch_id,p_code,p_name_ar,p_name_en,p_treasury_type,p_account_id,p_bank_name,p_bank_account_reference)$$;

create or replace function app_private.update_treasury_account_internal(p_treasury_account_id uuid,p_code text,p_name_ar text,p_name_en text,p_bank_name text,p_bank_account_reference text,p_is_active boolean) returns void language plpgsql security definer set search_path='' as $$
declare v_treasury public.treasury_accounts%rowtype; begin if auth.uid() is null then raise exception 'authentication required'; end if; select * into v_treasury from public.treasury_accounts where id=p_treasury_account_id for update; if not found then raise exception 'treasury account not found'; end if; if not app_private.has_permission('treasury.accounts.manage',v_treasury.branch_id,auth.uid()) then raise exception 'permission denied'; end if; if nullif(btrim(p_code),'') is null or nullif(btrim(p_name_ar),'') is null then raise exception 'treasury code and Arabic name required'; end if; if not coalesce(p_is_active,true) and exists(select 1 from public.treasury_movements where treasury_account_id=v_treasury.id) then raise exception 'cannot deactivate treasury account with movement history'; end if; update public.treasury_accounts set code=btrim(p_code),name_ar=btrim(p_name_ar),name_en=nullif(btrim(p_name_en),''),bank_name=case when treasury_type='bank' then nullif(btrim(p_bank_name),'') else null end,bank_account_reference=case when treasury_type='bank' then nullif(btrim(p_bank_account_reference),'') else null end,is_active=coalesce(p_is_active,true),updated_by=auth.uid(),updated_at=now() where id=v_treasury.id; end $$;
create or replace function public.update_treasury_account(p_treasury_account_id uuid,p_code text,p_name_ar text,p_name_en text,p_bank_name text default null,p_bank_account_reference text default null,p_is_active boolean default true) returns void language sql security invoker set search_path='' as $$select app_private.update_treasury_account_internal(p_treasury_account_id,p_code,p_name_ar,p_name_en,p_bank_name,p_bank_account_reference,p_is_active)$$;

create or replace function app_private.create_treasury_movement_internal(p_branch_id uuid,p_treasury_account_id uuid,p_movement_date date,p_direction text,p_amount numeric,p_counter_account_id uuid,p_description text,p_reference text,p_idempotency_key text) returns uuid language plpgsql security definer set search_path='' as $$
declare v_treasury public.treasury_accounts%rowtype; v_counter public.accounts%rowtype; v_id uuid; v_number bigint; v_journal_id uuid; v_journal_number bigint; begin
 if auth.uid() is null then raise exception 'authentication required'; end if; if not app_private.has_permission('treasury.movements.create',p_branch_id,auth.uid()) then raise exception 'permission denied'; end if; if p_direction not in ('in','out') then raise exception 'invalid treasury movement direction'; end if; if coalesce(p_amount,0)<=0 then raise exception 'treasury movement amount must be positive'; end if; if nullif(btrim(p_description),'') is null then raise exception 'treasury movement description required'; end if; if nullif(btrim(p_idempotency_key),'') is null then raise exception 'idempotency key required'; end if;
 select id into v_id from public.treasury_movements where branch_id=p_branch_id and idempotency_key=btrim(p_idempotency_key); if found then return v_id; end if;
 select * into v_treasury from public.treasury_accounts where id=p_treasury_account_id and branch_id=p_branch_id; if not found or not v_treasury.is_active then raise exception 'active treasury account not found in branch'; end if; perform app_private.validate_treasury_coa_account_internal(p_branch_id,v_treasury.account_id);
 select * into v_counter from public.accounts where id=p_counter_account_id and branch_id=p_branch_id; if not found or not v_counter.is_active or not v_counter.is_postable then raise exception 'counter account must be active and postable'; end if; if v_counter.id=v_treasury.account_id then raise exception 'counter account must differ from treasury COA account'; end if;
 if p_direction='out' and (select coalesce(balance,0) from public.treasury_balances where branch_id=p_branch_id and treasury_account_id=p_treasury_account_id) < round(p_amount,2) then raise exception 'insufficient treasury balance'; end if;
 perform pg_advisory_xact_lock(hashtextextended('treasury:'||p_branch_id::text,0)); select coalesce(max(movement_number),0)+1 into v_number from public.treasury_movements where branch_id=p_branch_id; perform pg_advisory_xact_lock(hashtextextended('journal:'||p_branch_id::text,0)); select coalesce(max(entry_number),0)+1 into v_journal_number from public.journal_entries where branch_id=p_branch_id;
 insert into public.journal_entries(branch_id,entry_number,entry_date,status,memo,reference,idempotency_key,source_type,source_id,posted_at,posted_by,created_by,updated_by) values(p_branch_id,v_journal_number,coalesce(p_movement_date,current_date),'posted',btrim(p_description),nullif(btrim(p_reference),''),'treasury:'||btrim(p_idempotency_key),'treasury_movement',null,now(),auth.uid(),auth.uid(),auth.uid()) returning id into v_journal_id;
 insert into public.journal_lines(branch_id,journal_entry_id,line_no,account_id,debit,credit,description) values(p_branch_id,v_journal_id,1,case when p_direction='in' then v_treasury.account_id else v_counter.id end,round(p_amount,2),0,btrim(p_description)),(p_branch_id,v_journal_id,2,case when p_direction='in' then v_counter.id else v_treasury.account_id end,0,round(p_amount,2),btrim(p_description));
 insert into public.treasury_movements(branch_id,treasury_account_id,movement_number,movement_date,direction,amount,counter_account_id,description,reference,idempotency_key,journal_entry_id,created_by) values(p_branch_id,p_treasury_account_id,v_number,coalesce(p_movement_date,current_date),p_direction,round(p_amount,2),p_counter_account_id,btrim(p_description),nullif(btrim(p_reference),''),btrim(p_idempotency_key),v_journal_id,auth.uid()) returning id into v_id; update public.journal_entries set source_id=v_id where id=v_journal_id; return v_id; end $$;
create or replace function public.create_treasury_movement(p_branch_id uuid,p_treasury_account_id uuid,p_movement_date date,p_direction text,p_amount numeric,p_counter_account_id uuid,p_description text,p_reference text,p_idempotency_key text) returns uuid language sql security invoker set search_path='' as $$select app_private.create_treasury_movement_internal(p_branch_id,p_treasury_account_id,p_movement_date,p_direction,p_amount,p_counter_account_id,p_description,p_reference,p_idempotency_key)$$;

revoke all on function app_private.validate_treasury_coa_account_internal(uuid,uuid),app_private.create_treasury_account_internal(uuid,text,text,text,text,uuid,text,text),app_private.update_treasury_account_internal(uuid,text,text,text,text,text,boolean),app_private.create_treasury_movement_internal(uuid,uuid,date,text,numeric,uuid,text,text,text) from public,anon,authenticated;
revoke all on function public.create_treasury_account(uuid,text,text,text,text,uuid,text,text),public.update_treasury_account(uuid,text,text,text,text,text,boolean),public.create_treasury_movement(uuid,uuid,date,text,numeric,uuid,text,text,text) from public,anon;
grant execute on function public.create_treasury_account(uuid,text,text,text,text,uuid,text,text),public.update_treasury_account(uuid,text,text,text,text,text,boolean),public.create_treasury_movement(uuid,uuid,date,text,numeric,uuid,text,text,text) to authenticated;
