create table public.stock_count_sessions (
 id uuid primary key default gen_random_uuid(), branch_id uuid not null references public.branches(id), warehouse_id uuid not null,
 status text not null default 'draft' check(status in('draft','pending_approval','posted','rejected','cancelled')), note text,
 submitted_at timestamptz, submitted_by uuid references auth.users(id), created_by uuid not null default auth.uid() references auth.users(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,branch_id),
 foreign key(warehouse_id,branch_id) references public.warehouses(id,branch_id));
create table public.stock_count_lines (
 id uuid primary key default gen_random_uuid(), branch_id uuid not null references public.branches(id), session_id uuid not null,
 inventory_item_id uuid not null, system_quantity numeric not null, counted_quantity numeric not null check(counted_quantity>=0),
 variance_quantity numeric generated always as (counted_quantity-system_quantity) stored, observed_at timestamptz not null default now(),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,branch_id), unique(session_id,inventory_item_id),
 foreign key(session_id,branch_id) references public.stock_count_sessions(id,branch_id) on delete cascade,
 foreign key(inventory_item_id,branch_id) references public.inventory_items(id,branch_id));
create index idx_stock_count_sessions_branch_status on public.stock_count_sessions(branch_id,status,created_at desc);
create index idx_stock_count_sessions_warehouse_branch on public.stock_count_sessions(warehouse_id,branch_id);
create index idx_stock_count_sessions_created_by on public.stock_count_sessions(created_by);
create index idx_stock_count_sessions_submitted_by on public.stock_count_sessions(submitted_by) where submitted_by is not null;
create index idx_stock_count_lines_session_branch on public.stock_count_lines(session_id,branch_id);
create index idx_stock_count_lines_item_branch on public.stock_count_lines(inventory_item_id,branch_id);
create index idx_stock_count_lines_branch on public.stock_count_lines(branch_id);
alter table public.stock_count_sessions enable row level security; alter table public.stock_count_lines enable row level security;
create policy stock_count_sessions_select on public.stock_count_sessions for select to authenticated using(app_private.has_permission('inventory.count',branch_id,(select auth.uid())));
create policy stock_count_lines_select on public.stock_count_lines for select to authenticated using(app_private.has_permission('inventory.count',branch_id,(select auth.uid())));
revoke all on public.stock_count_sessions,public.stock_count_lines from anon,authenticated; grant select on public.stock_count_sessions,public.stock_count_lines to authenticated;
drop policy if exists warehouses_select on public.warehouses;
create policy warehouses_select on public.warehouses for select to authenticated using(app_private.current_user_may_access_branch(branch_id) and (app_private.current_user_has_permission('inventory.view',branch_id) or app_private.current_user_has_permission('procurement.purchases.receive',branch_id) or app_private.current_user_has_permission('inventory.count',branch_id)));
drop policy if exists inventory_items_select on public.inventory_items;
create policy inventory_items_select on public.inventory_items for select to authenticated using(app_private.current_user_may_access_branch(branch_id) and (app_private.current_user_has_permission('inventory.view',branch_id) or app_private.current_user_has_permission('procurement.purchases.view',branch_id) or app_private.current_user_has_permission('procurement.purchases.create',branch_id) or app_private.current_user_has_permission('procurement.purchases.edit',branch_id) or app_private.current_user_has_permission('procurement.purchases.submit',branch_id) or app_private.current_user_has_permission('procurement.purchases.cancel',branch_id) or app_private.current_user_has_permission('procurement.purchases.receive',branch_id) or app_private.current_user_has_permission('inventory.count',branch_id)));
create or replace function app_private.create_stock_count_session_internal(p_branch_id uuid,p_warehouse_id uuid,p_note text default null) returns uuid language plpgsql security definer set search_path='' as $$declare v_id uuid; begin if auth.uid() is null then raise exception 'authentication required'; end if; if not app_private.has_permission('inventory.count',p_branch_id,auth.uid()) then raise exception 'permission denied'; end if; perform 1 from public.warehouses w where w.id=p_warehouse_id and w.branch_id=p_branch_id and w.is_active; if not found then raise exception 'active warehouse not found in branch'; end if; insert into public.stock_count_sessions(branch_id,warehouse_id,note,created_by) values(p_branch_id,p_warehouse_id,nullif(btrim(p_note),''),auth.uid()) returning id into v_id; return v_id; end$$;
create or replace function public.create_stock_count_session(p_branch_id uuid,p_warehouse_id uuid,p_note text default null) returns uuid language sql security invoker set search_path='' as $$select app_private.create_stock_count_session_internal(p_branch_id,p_warehouse_id,p_note)$$;
create or replace function app_private.set_stock_count_line_internal(p_session_id uuid,p_inventory_item_id uuid,p_counted_quantity numeric) returns uuid language plpgsql security definer set search_path='' as $$declare v_session public.stock_count_sessions%rowtype; v_system numeric; v_id uuid; begin if auth.uid() is null then raise exception 'authentication required'; end if; select * into v_session from public.stock_count_sessions where id=p_session_id for update; if not found then raise exception 'stock count session not found'; end if; if not app_private.has_permission('inventory.count',v_session.branch_id,auth.uid()) then raise exception 'permission denied'; end if; if v_session.status<>'draft' then raise exception 'only draft count can be edited'; end if; if p_counted_quantity is null or p_counted_quantity<0 then raise exception 'counted quantity must be zero or positive'; end if; perform 1 from public.inventory_items i where i.id=p_inventory_item_id and i.branch_id=v_session.branch_id and i.is_active; if not found then raise exception 'active inventory item not found in branch'; end if; v_system:=app_private.current_stock_quantity(v_session.branch_id,v_session.warehouse_id,p_inventory_item_id); insert into public.stock_count_lines(branch_id,session_id,inventory_item_id,system_quantity,counted_quantity,observed_at) values(v_session.branch_id,v_session.id,p_inventory_item_id,v_system,p_counted_quantity,now()) on conflict(session_id,inventory_item_id) do update set system_quantity=excluded.system_quantity,counted_quantity=excluded.counted_quantity,observed_at=now(),updated_at=now() returning id into v_id; return v_id; end$$;
create or replace function public.set_stock_count_line(p_session_id uuid,p_inventory_item_id uuid,p_counted_quantity numeric) returns uuid language sql security invoker set search_path='' as $$select app_private.set_stock_count_line_internal(p_session_id,p_inventory_item_id,p_counted_quantity)$$;
create or replace function app_private.submit_stock_count_session_internal(p_session_id uuid) returns uuid language plpgsql security definer set search_path='' as $$declare v_session public.stock_count_sessions%rowtype; v_line record; v_current numeric; begin if auth.uid() is null then raise exception 'authentication required'; end if; select * into v_session from public.stock_count_sessions where id=p_session_id for update; if not found then raise exception 'stock count session not found'; end if; if not app_private.has_permission('inventory.count',v_session.branch_id,auth.uid()) then raise exception 'permission denied'; end if; if v_session.status='pending_approval' then return v_session.id; end if; if v_session.status<>'draft' then raise exception 'stock count is not submittable'; end if; if not exists(select 1 from public.stock_count_lines l where l.session_id=v_session.id) then raise exception 'stock count requires at least one line'; end if; for v_line in select * from public.stock_count_lines l where l.session_id=v_session.id order by l.id loop v_current:=app_private.current_stock_quantity(v_session.branch_id,v_session.warehouse_id,v_line.inventory_item_id); if v_current<>v_line.system_quantity then raise exception 'stock changed after count snapshot; recount item %',v_line.inventory_item_id; end if; end loop; update public.stock_count_sessions set status='pending_approval',submitted_at=now(),submitted_by=auth.uid(),updated_at=now() where id=v_session.id; return v_session.id; end$$;
create or replace function public.submit_stock_count_session(p_session_id uuid) returns uuid language sql security invoker set search_path='' as $$select app_private.submit_stock_count_session_internal(p_session_id)$$;
revoke all on function app_private.create_stock_count_session_internal(uuid,uuid,text),app_private.set_stock_count_line_internal(uuid,uuid,numeric),app_private.submit_stock_count_session_internal(uuid) from public,anon,authenticated;
revoke all on function public.create_stock_count_session(uuid,uuid,text),public.set_stock_count_line(uuid,uuid,numeric),public.submit_stock_count_session(uuid) from public,anon;
grant execute on function public.create_stock_count_session(uuid,uuid,text),public.set_stock_count_line(uuid,uuid,numeric),public.submit_stock_count_session(uuid) to authenticated;
